### ISSUE TITLE
Scoring system overhaul

### ISSUE THREAD

**Issue by speakerjohnash** [msevrens/Prophet-v1.0.0#5]
Truth scoring system needs to be overhauled before launch. Early work taking place here: https://github.com/msevrens/Mind/blob/master/mind/truth_scoring.py

## Todo
- [x] Get votes csv from database
- [x] Load thoughts and filter by prescience
- [x] Implement new truth rating widget
- [ ] Implement new time span collection widget
- [ ] Analytics

## Analytics
- [ ] How many thoughts have more than one truth vote?
- [ ] How many unique users have logged votes?
- [ ] How many thoughts have dissonance between users?
- [ ] What is the distribution of truth votes?

## Requirements

- [ ] Should reward more: correct contrarianism
- [ ] Should reward less: correct alignment with the crowd
- [ ] Should penalize more: incorrect contrarianism
- [ ] Should penalize less: incorrect alignment with the crowd
